#!/bin/bash

DIRECTORY="bin";
JAVA_CP="-classpath $CLASSPATH:$DIRECTORY";
MAIN_CLASS="gr/ntua/cslab/central/app/MainApplication";
SCRIPTS=10
DATASET_PATH="data/dataset"

K=2
QID=$(seq 1 8)


if [ $# -gt 0 ]; then
	SCRIPTS=$1
fi

for i in $(seq 1 $SCRIPTS); do
	echo -ne "$i\t"
	java $JAVA_CP $MAIN_CLASS \
		-f $DATASET_PATH/data$i.txt \
		-k $K \
		"-qid" $QID;
done;

exit 0
